import { readFile } from "node:fs/promises"
import { describe, expect, it } from "vitest"

describe("default guide prompts", () => {
  it("offers Headlong and integrates workflow requirements without repetition", async () => {
    const [matchPrompt, generatePrompt, optimizePrompt] = await Promise.all([
      readFile(new URL("../prompts/match.md", import.meta.url), "utf8"),
      readFile(new URL("../prompts/generate.md", import.meta.url), "utf8"),
      readFile(new URL("../prompts/optimize.md", import.meta.url), "utf8"),
    ])
    const normalizedGeneratePrompt = generatePrompt.replace(/\s+/gu, " ")

    expect(matchPrompt).toContain("Treat Headlong as a cross-cutting persistence option.")
    expect(matchPrompt).toContain("include Headlong among the five candidates")
    expect(matchPrompt).toContain("Do not force Headlong")
    expect(matchPrompt).toContain("Treat Poteto Mode as a cross-cutting structured-engineering option.")
    expect(matchPrompt).toContain("`$poteto-mode` hook marker and `$pstack-for-codex:poteto-mode` skill invocation")
    expect(matchPrompt).toContain("When both Headlong and Poteto Mode fit,")
    expect(matchPrompt).toContain("include both and use the third")
    expect(matchPrompt).toContain("position for the strongest task-specific alternative")
    expect(matchPrompt).toContain("Rank the user's requested outcome, not the amount of text")
    expect(matchPrompt).toContain("Treat\n`avoidFor` and unmet prerequisites as negative evidence")
    expect(matchPrompt).toContain("resolve the choice with\ntheir actual runtime differences")
    expect(matchPrompt).toContain("Do not reward a profile only because it lists more capabilities")
    expect(matchPrompt).toContain("must identify the matching user outcome or workflow strength")
    expect(matchPrompt).toContain("An explicit profile identity has priority.")
    expect(matchPrompt).toContain("Do not replace `native:fmx/pstack-workers` with")
    expect(matchPrompt).toContain("`native:cdx/pstack`")
    expect(matchPrompt).toContain("separately pins `sandbox:claude-council`,")
    expect(matchPrompt).toContain("`sandbox:claude-research`, and `native:cpx/hve`")
    expect(matchPrompt).toContain("do not\ninclude it in the ranked five")
    expect(generatePrompt).toContain("preserve those requirements naturally in every")
    expect(generatePrompt).toContain("do not repeat the same")
    expect(generatePrompt).toContain("pressure-test that idea and its implementation")
    expect(generatePrompt).toContain("subject of additional research")
    expect(generatePrompt).toContain("For `native:fmx/default`")
    expect(normalizedGeneratePrompt).toContain("supported fleet lifecycle")
    expect(normalizedGeneratePrompt).toContain("smallest useful durable task graph and worker count")
    expect(normalizedGeneratePrompt).toContain("promote an existing scout")
    expect(normalizedGeneratePrompt).toContain("durable status, wake, steering, blocker, and decision state")
    expect(normalizedGeneratePrompt).toContain("safe teardown")
    expect(generatePrompt).toContain("For `native:fmx/pstack-workers`")
    expect(generatePrompt).toContain("smallest logical change")
    expect(generatePrompt).toContain("Do\nnot invoke Poteto Mode")
    expect(generatePrompt).toContain("authored operating-contract prefix is")
    expect(generatePrompt).toContain("Do not add a second operating-contract section")
    expect(normalizedGeneratePrompt).toContain("Do not force unsupported or")
    expect(normalizedGeneratePrompt).toContain("secondmates, Relay, voice, Zellij, Orca")
    expect(generatePrompt).toContain("well-structured Markdown document")
    expect(generatePrompt).toContain("do not emit MDX, JSX, HTML")
    expect(optimizePrompt).toContain("Apply the loaded")
    expect(optimizePrompt).toContain("`prompt-master` skill")
    expect(optimizePrompt).toContain("same number of candidates")
    expect(optimizePrompt).toContain("Preserve and improve useful Markdown structure")
  })
})
